FROM rockylinux:8.9

# Install R
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN dnf upgrade --refresh -y
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-8.noarch.rpm
RUN curl -O https://cdn.rstudio.com/r/centos-8/pkgs/R-4.2.3-1-1.x86_64.rpm
RUN yum install -y R-4.2.3-1-1.x86_64.rpm

# Configure the default repo to use linux binaries
RUN echo 'options(repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/centos8/latest"))' > opt/R/4.2.3/lib/R/etc/Rprofile.site

CMD ["/opt/R/4.2.3/bin/R"]